name: First Workflow
on:
  workflow_dispatch:
  workflow_call:

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "hello"
      - name: print goodbye
        run: echo "done - goodbye"
